
baseURL = "https://coffeesongtrang.com"
title = "Cà Phê - Điểm Tâm - Cơm Văn Phòng"
theme = "cfgarden"

languageCode = "vi-VN"
DefaultContentLanguage = "vi"
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Coffee Sông Trăng"
  facebook = "https://facebook.com/coffeesongtrang"
  og_image = "/images/og.png"
  sitename = "Coffee Sông Trăng"
  description = "s"
  twitter = "@coffeesongtrang"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[taxonomies]
  category = "categories"
  tag = "tags"